export const filterBlankLines = (arr) => {
  return arr.filter(
    (line) => !line.split("").every((char) => /\s|\n|\t/.test(char))
  );
};

export const configText = [
  [
    "Bonjour! Je suis Monsieur Clippe, and I will aide vous to configure les boutons. Press any touche to continue.",
    "Alors, first please press the touche - ah, I mean the key - that you want to mean OUI.",
    "Très bien! Now please choisir the key to mean NON.",
    "Et finalment, which touche voulez-vous for the bouton défaire? Ah, pardon! Je vais dire the UNDO button.",
    "Bien joué, et au revoir!",
    "Merci!",
    "D'accord",
  ],
  [
    "Guten tag! Ich bin Herr Klip, and I will help you zu konfigurieren the buttons. Drücken Sie any key to continue.",
    "Lasst uns beginnen! First please drücken - ah, I mean press - the key that you want to mean JA.",
    "Fantastisch! Please choose the Taste you want to mean NEIN.",
    "Und endlich, which Taste do you want as the Rückgängig? Ach, entschuldige! Ich meine the UNDO button.",
    "Gut gemacht, und auf Wiedersehen!",
    "Danke!",
    "Gut",
  ],
  [
    "Hola! Yo soy Señor Clipedro, and I will help you configurar los botones. Press any tecla to continue.",
    "Pues, to start please press the tecla - ay, quiero decir the key - that you want to mean SÍ.",
    "Genial! Ahora, por favor, choose the key to mean NO.",
    "Y al fin, which tecla quieres for the botón deshacer? Aj, disculpe! Eso es the UNDO button.",
    "Bien hecho, y adios!",
    "Gracias!",
    "Vale",
  ],
  [
    "Ciao! Io sono il Signor Clippiato, and I will help you configure the pulsanti. Press any key per continuare.",
    "Bene, to start please premere - oh, voglio dire press - the key that you want to mean SÍ.",
    "Fantastico! E ora please choose the tasto to mean NO.",
    "E infine, which tasto vuoi for the Pulsante Annulla? Oh, scusa! I mean the UNDO button.",
    "Ben fatto, e arrivederci!",
    "Grazie!",
    "Va bene",
  ],

  [
    "Hullo, ma name's Mr MacClip. A'm here tae help ye configure the buttons. Press any key tae continue.",
    "Richt then, tae start, press the key ye want tae mean AY.",
    "Guid, now choose the key tae mean NAW.",
    "An finally, which key dae ye want for the UNDAE button?",
    "Hae a guid day, an see ye efter!",
    "Thank ye!",
    "Ay.",
  ],
];

export const keys = {
  "8": "⌫",
  "9": "⇆",
  "13": "⏎",
  "16": "⇧",
  "17": "ctrl",
  "18": "alt",
  "19": "⏸",
  "20": "⇪",
  "27": "esc",
  "32": "⎵",
  "33": "pgup",
  "34": "pgdn",
  "35": "end",
  "36": "home",
  "37": "←",
  "38": "↑",
  "39": "→",
  "40": "↓",
  "45": "ins",
  "46": "del",
  "48": "0",
  "49": "1",
  "50": "2",
  "51": "3",
  "52": "4",
  "53": "5",
  "54": "6",
  "55": "7",
  "56": "8",
  "57": "9",
  "65": "A",
  "66": "B",
  "67": "C",
  "68": "D",
  "69": "E",
  "70": "F",
  "71": "G",
  "72": "H",
  "73": "I",
  "74": "J",
  "75": "K",
  "76": "L",
  "77": "M",
  "78": "N",
  "79": "O",
  "80": "P",
  "81": "Q",
  "82": "R",
  "83": "S",
  "84": "T",
  "85": "U",
  "86": "V",
  "87": "W",
  "88": "X",
  "89": "Y",
  "90": "Z",
  "91": "↞",
  "92": "↠",
  "93": "sel",
  "96": "n0",
  "97": "n1",
  "98": "n2",
  "99": "n3",
  "100": "n4",
  "101": "n5",
  "102": "n6",
  "103": "n7",
  "104": "n8",
  "105": "n9",
  "106": "*",
  "107": "+",
  "109": "-",
  "110": ".",
  "111": "/",
  "112": "f1",
  "113": "f2",
  "114": "f3",
  "115": "f4",
  "116": "f5",
  "117": "f6",
  "118": "f7",
  "119": "f8",
  "120": "f9",
  "121": "f10",
  "122": "f11",
  "123": "f12",
  "144": "num",
  "145": "scroll",
  "186": ";",
  "187": "=",
  "188": ",",
  "189": "-",
  "190": ".",
  "191": "/",
  "192": "'",
  "219": "[",
  "220": "\\",
  "221": "]",
  "222": "´",
  "223": "`",
  "225": "alt gr",
};

export const animals = [
  "alligator",
  "bear",
  // "W",
  // "WW",
  // "WWW",
  // "WWWW",
  // "WWWWW",
  // "Lorem ipsum: HEY HO LET'S GO to the great graveyard where the worm man lives, oh yes he is a man in the daytime but by night he is a moth and he flies to the light of a bar where he laps up the brown fizz.",
  // "WWWWWW",
  // "WWWWWWW",
  // "WWWWWWWW",
  // "WWWWWWWWW",
  // "WWWWWWWWWWW",
  // "WWWWWWWWWWWW",
  // "1MWMWMWMWMWMWMWMWMWMWMWMWMWM",
  // "2WMWMWMWMWMWMWMWMWMWMWMWMWMWM",
  // "3WMWMWMWMWMWMWMWMWMWMWMWMWMWM",
  // "4WMWMWMWMWMWMWMWMWMWMWMWMWMWM",
  // "5WMWMWMWMWMWMWMWMWMWMWMWMWMWM",
  // "6WMWMWMWMWMWMWMWMWMWMWMWMWMWM",
  // "Lorem ipsum: Under the grass where the worms live is a cave where only a nomad knows.",
  // "WMWMWMWMWMWMWMWMWMWMWMWMWMWM",
  "cat",
  "dog",
  "elephant",
  "fox",
  "goat",
  "horse",
  "iguana",
  "jackrabbit",
  "kangaroo",
  "lemur",
  "moray eel",
  "narhwal",
  "orangutan",
  "pangolin",
  "quail",
  "ram",
  "snake",
  "tapir",
  "ungulates in general",
  "viper",
  "whale",
  "xoloitzcuintle dog",
  "yak",
  "zebra",
];
